#!/usr/bin/env node
// send-email.mjs — Sends the generated signal email via Gmail SMTP

import { readFileSync } from "fs";
import { createTransport } from "nodemailer";

const { GMAIL_USER, GMAIL_APP_PASSWORD, RECIPIENT_EMAIL } = process.env;

if (!GMAIL_USER || !GMAIL_APP_PASSWORD || !RECIPIENT_EMAIL) {
  console.error("Missing email credentials. Required: GMAIL_USER, GMAIL_APP_PASSWORD, RECIPIENT_EMAIL");
  process.exit(1);
}

async function main() {
  const html = readFileSync("/tmp/signal-email.html", "utf-8");
  const data = JSON.parse(readFileSync("/tmp/signal-data.json", "utf-8"));

  const { assignments } = data;
  const date = new Date().toLocaleDateString("en-US", { month: "short", day: "numeric" });

  // Build a plain-text summary for email subject
  const subject = `[Signal ${date}] ⚡${assignments.tacticalBuy} 📐${assignments.positionalBuy} 🏗️${assignments.strategicBuy} ✂️${assignments.trim}`;

  // Plain text fallback with rankings
  const rankingText = data.normalized
    ? [...data.normalized]
        .sort((a, b) => (a.z?.composite ?? 0) - (b.z?.composite ?? 0))
        .map((s, i) => {
          const role =
            s.symbol === assignments.tacticalBuy   ? "TAC BUY" :
            s.symbol === assignments.positionalBuy  ? "POS BUY" :
            s.symbol === assignments.strategicBuy   ? "STR BUY" :
            s.symbol === assignments.trim           ? "TRIM" : "HOLD";
          const km = s.key_metric ? `${s.key_metric.name}: ${s.key_metric.value}` : "";
          const price = s.price?.current ? `$${s.price.current.toFixed(2)}` : "—";
          return `  ${String(i+1).padStart(2)}. ${s.symbol.padEnd(7)} ${price.padStart(10)}  Comp:${String(s.composite?.score ?? 0).padStart(4)}  T:${String(s.tactical?.score ?? 0).padStart(4)} P:${String(s.positional?.score ?? 0).padStart(4)} S:${String(s.strategic?.score ?? 0).padStart(4)}  [${role.padEnd(7)}]  ${km}`;
        }).join("\n")
    : "";

  const plainText = `PORTFOLIO STRATEGY SIGNAL — ${date}

═══════════════════════════════════════
  TACTICAL BUY:   ${assignments.tacticalBuy}
  POSITIONAL BUY: ${assignments.positionalBuy}
  STRATEGIC BUY:  ${assignments.strategicBuy}
  TRIM:           ${assignments.trim}
═══════════════════════════════════════

COMPOSITE RANKINGS (1=best buy, 11=weakest):
${rankingText}

Generated by Portfolio Strategy Hub v2.0`;

  const transporter = createTransport({
    service: "gmail",
    auth: {
      user: GMAIL_USER,
      pass: GMAIL_APP_PASSWORD,
    },
  });

  const info = await transporter.sendMail({
    from: `Portfolio Hub <${GMAIL_USER}>`,
    to: RECIPIENT_EMAIL,
    subject,
    text: plainText,
    html,
  });

  console.log(`✓ Email sent: ${info.messageId}`);
  console.log(`  To: ${RECIPIENT_EMAIL}`);
  console.log(`  Subject: ${subject}`);
}

main().catch(e => { console.error("Email send failed:", e); process.exit(1); });
